#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Jan 05, 2023 10:44:49 AM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import list_mac_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("800x350+342+98")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("尋找未重複MAC")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.063, rely=0.143, height=39, width=148)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Forescout檔案:''')
        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.125, rely=0.323, height=26, width=87)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''GCB清單:''')
        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.238, rely=0.143, height=34, width=88)
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''選擇檔案''')
        self.Button2 = tk.Button(self.top)
        self.Button2.place(relx=0.238, rely=0.286, height=34, width=88)
        self.Button2.configure(activebackground="beige")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''選擇檔案''')
        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.35, rely=0.109, relheight=0.311, relwidth=0.606)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Label_filename1 = tk.Label(self.Frame1)
        self.Label_filename1.place(relx=0.021, rely=0.183, height=31, width=464)
        self.Label_filename1.configure(activebackground="#f9f9f9")
        self.Label_filename1.configure(anchor='w')
        self.Label_filename1.configure(background="#d9d9d9")
        self.Label_filename1.configure(compound='left')
        self.Label_filename1.configure(disabledforeground="#a3a3a3")
        self.Label_filename1.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Label_filename1.configure(foreground="#000000")
        self.Label_filename1.configure(highlightbackground="#d9d9d9")
        self.Label_filename1.configure(highlightcolor="black")
        self.Label_filename2 = tk.Label(self.Frame1)
        self.Label_filename2.place(relx=0.021, rely=0.642, height=24, width=437)
        self.Label_filename2.configure(activebackground="#f9f9f9")
        self.Label_filename2.configure(anchor='w')
        self.Label_filename2.configure(background="#d9d9d9")
        self.Label_filename2.configure(compound='left')
        self.Label_filename2.configure(disabledforeground="#a3a3a3")
        self.Label_filename2.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Label_filename2.configure(foreground="#000000")
        self.Label_filename2.configure(highlightbackground="#d9d9d9")
        self.Label_filename2.configure(highlightcolor="black")
        self.Button_createList = tk.Button(self.top)
        self.Button_createList.place(relx=0.038, rely=0.486, height=34
                , width=248)
        self.Button_createList.configure(activebackground="beige")
        self.Button_createList.configure(activeforeground="black")
        self.Button_createList.configure(background="#d9d9d9")
        self.Button_createList.configure(compound='left')
        self.Button_createList.configure(disabledforeground="#a3a3a3")
        self.Button_createList.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Button_createList.configure(foreground="#000000")
        self.Button_createList.configure(highlightbackground="#d9d9d9")
        self.Button_createList.configure(highlightcolor="black")
        self.Button_createList.configure(pady="0")
        self.Button_createList.configure(text='''產生MAC列表.csv''')
        self.Button_Result = tk.Button(self.top)
        self.Button_Result.place(relx=0.038, rely=0.629, height=34, width=248)
        self.Button_Result.configure(activebackground="beige")
        self.Button_Result.configure(activeforeground="black")
        self.Button_Result.configure(background="#d9d9d9")
        self.Button_Result.configure(compound='left')
        self.Button_Result.configure(disabledforeground="#a3a3a3")
        self.Button_Result.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Button_Result.configure(foreground="#000000")
        self.Button_Result.configure(highlightbackground="#d9d9d9")
        self.Button_Result.configure(highlightcolor="black")
        self.Button_Result.configure(pady="0")
        self.Button_Result.configure(text='''合併廠商資料並輸出結果''')
        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label5 = tk.Label(self.top)
        self.Label5.place(relx=0.05, rely=0.743, height=30, width=244)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''輸入要回填資料的欄位名稱:''')
        self.Text_cloumnName = tk.Text(self.top)
        self.Text_cloumnName.place(relx=0.363, rely=0.743, relheight=0.086
                , relwidth=0.28)
        self.Text_cloumnName.configure(background="white")
        self.Text_cloumnName.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Text_cloumnName.configure(foreground="black")
        self.Text_cloumnName.configure(highlightbackground="#d9d9d9")
        self.Text_cloumnName.configure(highlightcolor="black")
        self.Text_cloumnName.configure(insertbackground="black")
        self.Text_cloumnName.configure(selectbackground="#c4c4c4")
        self.Text_cloumnName.configure(selectforeground="black")
        self.Text_cloumnName.configure(wrap="word")
        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.763, rely=0.457, height=44, width=158)
        self.Button3.configure(activebackground="beige")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(compound='left')
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Microsoft JhengHei UI} -size 14")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''一鍵產生文件''')

def start_up():
    list_mac_support.main()

if __name__ == '__main__':
    list_mac_support.main()




